on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testmscluster1registry.azurecr.io
        username: ${{ secrets.acr_testmscluster1registry_username }}
        password: ${{ secrets.acr_testmscluster1registry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AppService/node_express_sampleApp" -f  "AppService/node_express_sampleApp/Dockerfile" -t testmscluster1registry.azurecr.io/testmscluster1:${{ github.sha }} --label dockerfile-path=AppService/node_express_sampleApp/Dockerfile
        docker push testmscluster1registry.azurecr.io/testmscluster1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testmscluster1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testms_cluster1ab84 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testms_cluster1ab84`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testms_cluster1ab84
        container-registry-url: testmscluster1registry.azurecr.io
        container-registry-username: ${{ secrets.acr_testmscluster1registry_username }}
        container-registry-password: ${{ secrets.acr_testmscluster1registry_password }}
        secret-name: testmsclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testms_cluster1ab84
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          testmscluster1registry.azurecr.io/testmscluster1:${{ github.sha }}
        imagepullsecrets: |
          testmsclustedockerauth
